### ISSUE TITLE
URL detection stops at character '

### ISSUE THREAD

**Issue by NicHub** [leonid-shevtsov/ClickableUrls_SublimeText#23]
That means the plugin cannot open this URL for example:

http://fr.wikipedia.org/wiki/Liste_des_logiciels_CAO_pour_l'architecture,_l'ingénierie_et_la_construction

**Comment by leonid-shevtsov** [comment]
I will add the quote character to the URL regex, but the bad news is - it's going to stop at "é".

URL regexes are tricky, and I picked a robust but simple one. [There's a more complete regex here](https://gist.github.com/dperini/729294), but it's not a straightforward port to Sublime Text - and not to Python, because instead of compiling the regex on the plugin's side I have to pass it as a string to Sublime Text's matcher engine.

**Comment by NicHub** [comment]
Thank you for your help. I hope you’ll find a good solution too.
