### ISSUE TITLE
Detect all kinds of URLs

### ISSUE THREAD

**Issue by hoeni** [leonid-shevtsov/ClickableUrls_SublimeText#32]
As an example: I use Devonthink for my research work and would like to keep references to some documents inside the things I write with Sublime Text like x-devonthink-item://3CD96079-4B91-47F7-BDE4-B0AC931AF87F?page=36

This kind of URL is not recognized by this module though registered in the system and in the browser. It could be easily just passed to the web browser for example, as the web browser will pass it to the right application (at least it does when I paste the url in its location bar).

I'd recommend highlighting all things that match the URI scheme and leave it to the browser to to the right thing [tm] opening them.

**Comment by FichteFoll** [comment]
Actually, URI schemas are registered on an OS level.

**Comment by mjknght** [comment]
Hello there. I think it should be possible to update the regex in `clickable_urls.py` to find any kind of URL. I've just installed the Package, and wanted the same functionality. But since I was only interested in a few different URL schemas, I opted for the quick fix of specifying those in the regex instead, changing the default to:

`\\b(http|message|file)s?:///?[-A-Za-z0-9+&@#/%?=~_()|!:,.;']*[-A-Za-z0-9+&@#/%=~_(|]"`

Leaving this here incase it is of any use!
